[broker]
host = "localhost"
port = 1883
protocol = "tcp"

type = "mqtt"
topic = "edgex/events/#"
client_id = "EdgeXClient-Test"
username = "your-username"  # 可选
password = "your-password"  # 可选
publish = true
publish_interval = 10
log_level = "INFO"
